# Generated by Django 4.2.7 on 2023-11-21 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=200, verbose_name='Sobrenome')),
                ('date_of_birth', models.DateField(verbose_name='Data de nascimento')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Número de telefone')),
                ('address', models.CharField(max_length=254, verbose_name='Endereço')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(verbose_name='Imagem')),
                ('name', models.CharField(max_length=254, verbose_name='Nome')),
                ('amount', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SaleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(verbose_name='Número de Pedido')),
                ('amount_buy', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('sale_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vendido em')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordereds', to='core.clientmodel', verbose_name='Cliente')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordereds', to='core.productmodel', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['order_number'],
            },
        ),
    ]
