# Generated by Django 4.2.7 on 2023-11-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemodel',
            name='order_number',
            field=models.CharField(max_length=4, verbose_name='Número de Pedido'),
        ),
    ]
